name: sd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip:
    - accelerate
    - diffusers  
    - tqdm
    - opencv-python
    - transformers
  - numpy  
  - pytorch 
  - torchvision 
  - torchaudio 
  - ftfy
  - pytorch-cuda
